# Change these first
owner: CloudDefenseAI # Your GitHub organization or username, where this repository lives
repo: upptime-monitor # The name of this repository

sites:
  - name: CloudDefense.AI
    url: https://www.clouddefense.ai
  - name: CloudDefense.AI DevSecOps Portal(US)
    url: https://console.clouddefenseai.com
  - name: CloudDefense.AI CloudSec Portal(US)
    url: https://acs-us.clouddefenseai.com
  - name: CloudDefense.AI DevSecOps Portal(IND)
    url: https://console-ind.clouddefenseai.com
  # - name: CloudDefense.AI DevSecOps Portal(UAE)
  #   url: https://uae.clouddefenseai.com
  # - name: CloudDefense.AI CloudSec Portal(UAE)
  #   url: https://acs-uae.clouddefenseai.com
  - name: CloudDefense.AI DevSecOps Portal(QA)
    url: https://qa.clouddefenseai.com
  - name: CloudDefense.AI CloudSec Portal(QA)
    url: https://acs-qa.clouddefenseai.com
  - name: CloudDefense.AI DevSecOps Portal(DEV)
    url: https://dev.clouddefenseai.com
  - name: CloudDefense.AI CloudSec Portal(DEV)
    url: https://acs-dev.clouddefenseai.com
  # - name: IPv6 test
  #   url: forwardemail.net
  #   port: 80
  #   check: "tcp-ping"
  #   ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime-monitor.clouddefenseai.com
  # baseUrl: /your-repo-name
  logoUrl: https://www.clouddefense.ai/wp-content/uploads/2023/09/Green-iconwhite-text-vertical.png
  name: Upptime
  introTitle: "**CloudDefense.AI** uptime monitor and status page"
  introMessage: This is a **CloudDefense.AI** status page which uses **real-time** data.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
